on: push
jobs:
  dissertation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: |
          npm ci
          npm run build
        working-directory: dissertation
      - uses: actions/upload-artifact@v1
        with:
          name: Dissertation
          path: dissertation/yocto-cfa.pdf
  code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm install-ci-test
        working-directory: code
